### ISSUE TITLE
HTML Entity codes are being displayed raw

### ISSUE THREAD

**Issue by Eboubaker** [LibreTranslate/LibreTranslate#203]
Here result should be: `entité n'a pas été supprimée` but the apostrophe entity code is being displayed as raw html

![image](https://user-images.githubusercontent.com/37766821/151781527-ff5e9563-3544-46dd-b78b-f64c4ea0c57f.png)
Input : `entity was not Removed` with big `R`  letter

**Comment by dingedi** [comment]
after checking the bug is not always present, would it not be a bug of argos rather? @PJ-Finlay 

![image](https://user-images.githubusercontent.com/64697405/151782777-73454f49-eab6-496a-95e3-3fec7873d3c1.png)

**Comment by PJ-Finlay** [comment]
The issue is that the [CTranslate2](https://github.com/OpenNMT/CTranslate2) seq2seq sometimes generates these entity codes because there are entity codes in the training data.

Previously when we had this issue I added a filter in the training scripts to remove them but removed it because it was slow. I'm hoping that by using more and better data the model is able to figure out not to do this on its own. If this becomes a common issue we can try adding more data with apostrophes and other HTML entities being translated correctly as Unicode.

**Comment by PJ-Finlay** [comment]
https://github.com/argosopentech/argos-translate/issues/39

**Comment by Eboubaker** [comment]
Is it possible if you add the temporary filter in the frontend, so it won't affect the backend.

**Comment by PJ-Finlay** [comment]
A front end filter is possible. The issue with filtering them from the data is that searching millions of lines took a long time and was slowing down training.

**Comment by dingedi** [comment]
I'll try to take care of it this week if I have time. It will indeed fix this bug for libretranslate but it will still be present in argos.
would it be interesting to add the filter to the output of the argos translation @PJ-Finlay ?

**Comment by PJ-Finlay** [comment]
For Argos Translate I want to stick with the strategy of fixing this with better models but I think this filtering would be valuable to have in LibreTranslate.

**Comment by dingedi** [comment]
> For Argos Translate I want to stick with the strategy of fixing this with better models but I think this filtering would be valuable to have in LibreTranslate.

Okay yes i think its better than adding fix for each translations bug
