### ISSUE TITLE
English -> Turkish translate malicious result/s

### ISSUE THREAD

**Issue by wiseweb-works** [LibreTranslate/LibreTranslate#282]
![Ekran görüntüsü 2022-06-30 225903](https://user-images.githubusercontent.com/69072094/176778090-7c990fac-e018-4a8e-8793-f7401825068a.png)
Dear LibreTranslate project managers, while deleting a text that I translated, I came across a translation response that references a video site that produces adult content while only the word **"CUT"** remains. While by no means close to the correct translation, the correct translation (in Turkish lang) would be "kes/kesmek". Thus, such malicious responses may have been embedded in this word (and perhaps) translation of other words as well. I don't know the exact working system of your project, but if it includes machine learning, it may have been deliberately tried to teach the wrong answer. I'm reporting this under the **BUG** heading. Good day to all employees. If you need help, I'd be happy to help.

Edit: Added other related issue link. #141

**Comment by PJ-Finlay** [comment]
In general I think we want to translate profanity correctly but don't want to generate it unsolicited like this.

In this specific case and the linked ticket we're generating porn website names when unrelated words were entered. I think what's happening here is that the datasets used for training the models are scraped from the internet, which has a lot of porn, so some random words are being translated as porn site names. I'm also curious how common this situation is. Are we mistakingly translating a lot of things as "xHampster" or just getting reports the few times it does happened.

I think we could solve this specific case by removing porn site names from the data, but that's not a very generic solution. I previously did some data filtering at training time for Argos Translate but removed it because it was slow to do on every training run. Let me know if anyone has suggestions for doing filtering or data improvement well. We could keep a blacklist of character strings to remove, a set of transformation functions to apply to the training data, or something else.

Issues of the model generating clearly incorrect responses like this should also be improved by a general increase in model performance.

We could also consider an option for a a profanity filter after the translation has been performed in LibreTranslate. This could be done with a simple blacklist of words and could be useful for settings where you never want profanity.

**Comment by wiseweb-works** [comment]
I couldn't find any suggestions about datasets. However, I thought of a faster and more reasonable solution for filtering model. For example, can we filter "x***" and similar words during the display results process, not the learning process? Thus, it is not necessary to check for all input in every learning process. And maybe we don't waste time every time for entries that no one will search (or will not be searched much). For example, the result is the same every time you add a letter from the word "[denemeb](https://libretranslate.com/?source=en&target=tr&q=denemeb)" (means test b) to the word "[denemebubirdenememesajı](https://libretranslate.com/?source=en&target=tr&q=denememesaj%25C4%25B1bubirdenememesaj%25C4%25B1)" (means test this is a test message). The result is "x***.com". Definitely not a conscious search and true answer. Maybe, you want to add a button for such unsolicited results in the result screen. I can help you with words that will definitely not appear on the result screen in the Turkish language. If you have an existing list, I can voluntarily add/remove or approve/reject. Or an alternative thought?

**Comment by pierotofy** [comment]
> For example, can we filter "x***" and similar words 

Here lies the challenge; which words?

> In general I think we want to translate profanity correctly but don't want to generate it unsolicited like this.

Agree with this :+1:

**Comment by wiseweb-works** [comment]
@pierotofy I think we can start by adding words one by one. For example, if it is possible to filter regardless of upper and lower case, it would be better. We start by adding the "X...". The list grows as the reporting/issue arrives. Just like libretranslate is getting better and more consistent. According to the tests I made during the day, there are harmless and false results. For example, if you write "merhaba nasılsınız" (means hello how are you), the [translation result](https://libretranslate.com/?source=en&target=tr&q=merhaba%2520nas%25C4%25B1ls%25C4%25B1n%25C4%25B1z) will be "azərbaycanca" (means Azerbaijanese / Azerbaijani). I think it didn't attract attention before because it is a query that shouldn't be searched in English-Turkish translation. Because I chose English (Translate from) and wrote a Turkish sentence. This is also an incorrect translation. But I don't think it's as much of a problem as the others. Here is the list for now, along with other results I found during the day:

1. x***
2. x.***.com
3. azərbaycanca.
4. menü/Menü
5. türkçe/Türkçe

**Comment by EmanuelLoos** [comment]
This issue is not exclusive to Turkish and I am afraid a blacklist probably will not really solve it, since the translation AI seems biased from an unbalanced training dataset. It will interpret everything in a way which is too much sexual. It may be easy to filter out domains of porn sites, however, this does not address the bias which manifests itself in translations in many ways.

One thing I noticed is that Argos Translate currently ignores context. At least for long texts, detecting context and translating differently based on that could avoid this issue for texts where it is completely inappropriate.

An example I stumbled upon:
When translating [these lyrics](https://duckduckgo.com/?q=Angel+-+Jackie+Evancho+lyrics&ia=lyrics&iax=lyrics) to German it currently translates the word "[reverie](https://en.wiktionary.org/wiki/reverie#English)" as, well, "underwear". When typing in "reverie" alone it says "red wine". The word has been in Wiktionary for many years. (Argos Translate also uses Wiktionary data for training, right?)

Blacklisting words like "underwear" would not make much sense. It may even be the valid translation in some cases.

To me it seems, this can only be addressed with a better and more balanced dataset, context detection and other deep changes. Effectively filtering biases out at the surface would require an AI on its own.
