### ISSUE TITLE
Some languages should not be displayed if no "pivoting" model is available.

### ISSUE THREAD

**Issue by dingedi** [LibreTranslate/LibreTranslate#328]
I just noticed that all installed languages are displayed, however if "pivot" models are not installed it can cause this error

Example of installed models:
- **en -> es**
- **es -> en**
- **en -> nl**

The **nl -> es** translation will therefore not work because no model is installed for

![image](https://user-images.githubusercontent.com/64697405/193455249-6af2843d-6a20-49cd-b4c8-7a6c169be585.png)

**Comment by dingedi** [comment]
To solve this it would be necessary to modify the fetching of the languages and fetch all the directions of translation including the possible pivots.
Which would surely create a breaking change at **/languages**

I saw that the **[Language](https://github.com/argosopentech/argos-translate/blob/master/argostranslate/translate.py#L116)** class of argostranslate has two attributes **translations_from** and **translations_to** so it shouldn't be too complicated

**Comment by dingedi** [comment]
Yes it can be a good idea

**Comment by PJ-Finlay** [comment]
I noticed en->ca is currently broken with a similar issue on [libretranslate.com](https://libretranslate.com). This is occuring because ca->en is installed so English and Catalan are displayed in the user interface as available then fail when you try to translate English to Catalan.

We should figure out a good way to deal with this type of issue. In future versions of Argos Translate I'm planning to move to [multilingual models](https://community.libretranslate.com/t/multilingual-translation-with-ctranslate2-and-pre-trained-fairseq-models/178) so this should happen less frequently. I think the best solution is probably to have a better error response at the API level and more descriptive feedback in the graphic user interface.

We could have a `language_pairs` endpoint that returns something like this:
```
[[en, ca],[ca,en],[en,es]]
```
One issue with this approach is that this list could become very long if we want to support 200+ languages in the future. The list would be O(n^2) for the number of languages n so 200^2=40000. I don't think this is a huge deal though, if the response is less than 1MB lots of other web applications are downloading larger JavaScript tracking scripts 😂.

Another solution would be to add an API endpoint to check if a language pair is supported. This could be a standalone endpoint or we could add functionality to mark an API request as a test and get a response telling you if it's valid.

**Comment by pierotofy** [comment]
> 200^2=40000.

Manageable, also needs to be computed just once at startup.

**Comment by dingedi** [comment]
Maybe use this structure instead?
```json
{
"en": ["ca", "es"]
"ca": ["en"]
}
```

it simplifies the search and will be more understandable

**Comment by PJ-Finlay** [comment]
Yes we do only have to send the informaton once so it's not a big issue.

A dictionary or a sorted list would be faster to search.

**Comment by pierotofy** [comment]
I've found that extending `/languages` to include an additional `targets` field should work without breaking backward compatibility and without needing an additional endpoint. I'll modify the JS client as well and do some checks server side. #358

```
[{"code":"en","name":"English","targets":[["it","ar","zh","nl","fi","fr","de","hi","hu","id","ga","ja","ko","pl","pt","ru","es","sv","tr","uk","vi","az","cs","eo","el","he","fa","sk","da","en"]]},{"code":"ar","name":"Arabic","targets":[["en","ar","it","zh","nl","fi","fr","de","hi","hu","id","ga","ja","ko","pl","pt","ru","es","sv","tr","uk","vi","az","cs","eo","el","he","fa","sk","da"]]},{"code":"az","name":"Azerbaijani","targets":[["en","az","it","ar","zh","nl","fi","fr","de","hi","hu","id","ga","ja","ko","pl","pt","ru","es","sv","tr","uk","vi","cs","eo","el","he","fa","sk","da"]]}
```

**Comment by pierotofy** [comment]
Done!
